### ISSUE TITLE
ToDo + Status 01.12.21

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_schulserver#175]
- [ ] DHCP/DNS prüfen
- [ ] Monitoring ausrollen/testen + auf DX80 einrichten
- [ ] KVM prüfen "no signal"

zusätzlich:
- [ ] alle Playbooks ausrollen

**Comment by quotengrote** [comment]
Reiner DNS derzeit nicht möglich.
Zugang zum Netz nur über den Proxy.

**Comment by quotengrote** [comment]
Status:

- Alle Maschinen wurden geupdatet.
- DHCP funktioniert wieder
- "Internet" geht nur über den Proxy(genauer nur HTTP(S) über Port (8080)
- Mail(Port: 465/587) von den Servern geht nicht.
- Passwort `lehrer` musste neu gesetzt werden.

**Comment by quotengrote** [comment]
Bleibt offen da die BBS bis noch nicht die DNS-Problematik gelöst hat.
